import img from '@/assets/images/danchu_image.png';

export const projectData = [
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation:
      '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요! 날마다 쌓이는 단골의 추억 단추!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추2',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추2',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추2',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추2',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추2',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추2',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추3',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추3',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추3',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
  {
    isPrize: 1,
    imgUrl: img,
    projectName: '단추3',
    ordinalNumber: 13,
    contestName: '중앙톤',
    explanation: '지류 쿠폰을 디지털화하여 편리하게 관리하고 단골이 되어보세요!',
  },
];
